name: update_contrib

on:
  schedule:
    - cron: "0 0 * * 4"

jobs:
  update-contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: |
          npm i -g all-contributors-cli
          git fetch --prune --unshallow
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          git clone https://github.com/jina-ai/wall-of-honor.git .
          python app.py
          git commit -am 'chore: update contributors'
          git push